FROM postgres:latest

ENV DB_NAME = ecs_alb_db # 'postgres_kaustav' If the Initial Database Name was not inputted.
ENV DB_USER = postgres_kaustav
ENV DB_PASS = 123456789
ENV DB_HOST = ecs-fargate-db.ciik9jhczzrj.eu-north-1.rds.amazonaws.com
ENV DB_PORT = 8060